export const otherStateLinks: Record<string, string> = {
  Alabama: "/alabama/alabama-permit-practice-test/",
  Alaska: "/alaska/alaska-dmv-practice-test/",
  Arizona: "/arizona/az-permit-practice-test/",
  Arkansas: "/arkansas/arkansas-permit-practice-test/",
  California: "/california/dmv-practice-test/",
  Colorado: "/colorado/colorado-permit-practice-test/",
  Connecticut: "/connecticut/connecticut-permit-practice-test/",
  Delaware: "/delaware/dmv-delaware-practice-test/",
  "District of Columbia": "/district-columbia/dc-permit-practice-test/",
  Florida: "/florida/florida-permit-practice-test/",
  Georgia: "/georgia/georgia-permit-practice-test/",
  Hawaii: "/hawaii/hawaii-permit-practice-test/",
  Idaho: "/idaho/idaho-drivers-practice-test/",
  Illinois: "/illinois/illinois-permit-practice-test/",
  Indiana: "/indiana/indiana-bmv-practice-test/",
  Iowa: "/iowa/iowa-permit-practice-test/",
  Kansas: "/kansas/kansas-permit-practice-test/",
  Kentucky: "/kentucky/kentucky-dmv-practice-test/",
  Louisiana: "/louisiana/louisiana-permit-practice-test/",
  Maine: "/maine/maine-permit-practice-test/",
  Maryland: "/maryland/maryland-permit-practice-test/",
  Massachusetts: "/massachusetts/massachusetts-dmv-practice-test/",
  Michigan: "/michigan/michigan-permit-practice-test/",
  Minnesota: "/minnesota/minnesota-permit-practice-test/",
  Mississippi: "/mississippi/mississippi-permit-practice-test/",
  Missouri: "/missouri/missouri-permit-practice-test/",
  Montana: "/montana/montana-permit-practice-test/",
  Nebraska: "/nebraska/nebraska-dmv-practice-test/",
  Nevada: "/nevada/nevada-permit-practice-test/",
  "New Hampshire": "/new-hampshire/new-hampshire-permit-practice-test/",
  "New Jersey": "/new-jersey/new-jersey-practice-permit-test/",
  "New Mexico": "/new-mexico/new-mexico-permit-practice-test/",
  "New York": "/new-york/nys-permit-practice-test/",
  "North Carolina": "/north-carolina/north-carolina-permit-practice-test/",
  "North Dakota": "/north-dakota/north-dakota-permit-practice-test/",
  Ohio: "/ohio/ohio-permit-practice-test/",
  Oklahoma: "/oklahoma/oklahoma-permit-practice-test/",
  Oregon: "/oregon/oregon-permit-practice-test/",
  Pennsylvania: "/pennsylvania/pennsylvania-practice-permit-test/",
  "Rhode Island": "/rhode-island/rhode-island-dmv-practice-test/",
  "South Carolina": "/south-carolina/south-carolina-permit-practice-test/",
  "South Dakota": "/south-dakota/south-dakota-permit-practice-test/",
  Tennessee: "/tennessee/tennessee-permit-practice-test/",
  Texas: "/texas/texas-permit-practice-test/",
  Utah: "/utah/utah-permit-practice-test/",
  Vermont: "/vermont/vermont-permit-practice-test/",
  Virginia: "/virginia/virginia-permit-practice-test/",
  Washington: "/washington/washington-permit-practice-test/",
  "West Virginia": "/west-virginia/west-virginia-permit-practice-test/",
  Wisconsin: "/wisconsin/wisconsin-permit-practice-test/",
  Wyoming: "/wyoming/wyoming-permit-practice-test/",
};
